### ISSUE TITLE
Removed `use_frameworks! linkage: :static`

### ISSUE THREAD

**Issue by reichhartd** [tokenstreet-tech/react-native-idnow-videoident#141]
At the moment it is a necessary step to add in the `podfile` of the consumers of this library, the following line: `use_frameworks! linkage: :static`.

This is especially annoying in conjunction with React Native, because it makes [Flipper](https://github.com/facebook/flipper) stop working.
With the switch to the new React Native architecture, the web debugger is gone. So, if you use the new architecture and this library, you no longer have the option to use a debugger.

The person responsible for this issue should read about the different package types of Cocoapods, and find out if you can integrate the IDnow iOS SDK without `use_frameworks!`.
If this is not possible, it should be decided whether it makes sense from a package perspective to ship the IDnow iOS SDK in this form. If not, please create an issue in [their repository](https://github.com/idnow/de.idnow.ios).

Help for this issue is gratefully accepted.

**Comment by adityasingh773** [comment]
This is one of the reasons why I could not use the original id now react native wrapper from idnow. So, in your opinion if we want to continue using this library, we should get rid of Flipper?

**Comment by reichhartd** [comment]
Which original IDnow React Native wrapper do you mean? As far as I know, there are only unofficial ones.

In the [podfile of the React Native template](https://github.com/facebook/react-native/blob/c71e6efbcd2b95faee327d9763d321488120bc5e/template/ios/Podfile#L29-L30) is described that Flipper does not work with `use_frameworks!`. On the other hand, the [official Flipper documentation](https://fbflipper.com/docs/getting-started/ios-native/) defines a way to use Flipper with `use_frameworks!`:
```
  ...
  # If you use `use_frameworks!` in your Podfile,
  # uncomment the below $static_framework array and also
  # the pre_install section. This will cause Flipper and
  # it's dependencies to be built as a static library and all other pods to
  # be dynamic.
  #
  # NOTE Doing this may lead to a broken build if any of these are also transitive dependencies of other dependencies.
  # transitive dependencies of other dependencies and are expected
  # to be built as frameworks.
  #
  # $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
  # 'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
  # 'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
  # 'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native', 'Flipper-Fmt']
  #
  # pre_install do |installer|
  # pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  # installer.pod_targets.each do |pod|
  # if $static_framework.include?(pod.name)
  # def pod.build_type;
  # pod::BuildType.static_library
  # end
  # end
  # end
  # end
  ...
```
We have not tested this way yet, because it was not a priority. For the moment, we can work without Flipper. With the migration to the future React Native architecture, it will become necessary.

In the end, it is a business decision. Do you need the IDnow Video Ident integration or Flipper.

**Comment by adityasingh773** [comment]
Adding these lines in my podfile solved the build related issue.
```ruby
pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
        def pod.build_type;
          Pod::BuildType.static_library # >= 1.9
        end
      end
    end
  end
```
Also I meant this id now react native example: https://github.com/idnow/de.idnow.reactnative-wrapper

**Comment by reichhartd** [comment]
Which build related issue are you referring to? Is it possible for you to build a React Native application with the IDnow VideoIdent SDK and Flipper with this customisation?
And if so, could you describe exactly how to do it? Then I will add it to the documentation.

Your example is a React Native wrapper for the [AutoIdent product](https://www.idnow.io/products/idnow-autoident/). Our package is only for the [VideoIdent product](https://www.idnow.io/products/idnow-videoident/). Both products have different iOS SDKs: [AutoIdent SDK](https://github.com/idnow/de.idnow.ios.sdk) and [VideoIdent SDK](https://github.com/idnow/de.idnow.ios)

**Comment by reichhartd** [comment]
Created an issue in the IDnow iOS SDK repository: https://github.com/idnow/de.idnow.ios/issues/119

**Comment by reichhartd** [comment]
There is a workaround to get rid of `use_frameworks! linkage: :static` with the plugin `cocoapods-user-defined-build-types`. The way to do this is now [documented on the website](https://tokenstreet-tech.github.io/react-native-idnow-videoident/docs/cocoapods-build-types).
