### ISSUE TITLE
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityConcurrency'

### ISSUE THREAD

**Issue by adityasingh773** [tokenstreet-tech/react-native-idnow-videoident#151]
I have an already existing react native app and I am trying to install this library. But there is a problem with ios. I get the error message: Could not find or use auto-linked library 'swiftCompatibilityConcurrency' when building the app.

**To Reproduce**

1. Install the library
2. Update Podfile as per the instructions
3. The build fails with the above error message.

**Expected behavior**
Build succeeds.

**Screenshots**
<img width="895" alt="Screenshot 2022-03-17 at 12 40 09" src="https://user-images.githubusercontent.com/11049213/158801039-bae05472-0779-43c9-a908-d66b77743a11.png">

**Smartphone (please complete the following information):**

-   Device: Macbook Pro with M1 Chip
-   Xcode 13.1, Build version 13A1030d
-   React: 17.0.2, React Native: 0.66.3

**Comment by lennycampino** [comment]
Hi @adityasingh773,

I cannot reproduce the error myself.

Can you try the following things:
- Run the IOS build in Rosetta: e.g. `arch -x86_64 npm run ios`
- Upgrade to React Native Version 0.67.3
- Install the latest Xcode Version 13.3

**Comment by adityasingh773** [comment]
Updating my xcode and cocoapods solved the issue @lennycampino

**Comment by adityasingh773** [comment]
Updating my xcode and cocoapods solved the issue @lennycampino
