### ISSUE TITLE
Android does not proceed after "Start Identification" in production environment

### ISSUE THREAD

**Issue by adityasingh773** [tokenstreet-tech/react-native-idnow-videoident#226]
**Android does not proceed after "Start Identification" in production environment**
Everything works fine on development environment when we use "test" tokens from idnow. However, when you move to production, the android sdk wont proceed even after clicking multiple times (and with multiple other production tokens)

**To Reproduce**

1. Install library in a bare react native project
2. Follow android installation guidelines
3. Run on android device using production(live) token.
4. Enter phone number in the SDK, accept all 3 points
5. Click "Start Identification"
6. You are stuck.

**Expected behavior**
Verification is carried out after clicking on "Start Identification"

**Screenshots**
![Screenshot_2022-04-13-16-25-33-338_com tokenid](https://user-images.githubusercontent.com/11049213/163203336-62c9ffb7-9703-407a-adeb-bd134b6eb351.jpg)

**Smartphone (please complete the following information):**

-   Library version: "^0.5.0",
-   Android phone: Xiaomi Redmi Note 8

**Comment by reichhartd** [comment]
Hi @adityasingh773,
thanks for addressing this issue. We were able to reproduce it, and it appears to be a bug in the IDnow Android SDKs.
Please report this bug in the [IDnow Android repository](https://github.com/idnow/de.idnow.android), or to the mail tickets@idnow.de.
You are also welcome to link the issue created here in the IDnow repository. This way other developers can follow the progress.

**Comment by adityasingh773** [comment]
@reichhartd I created issue there. Leaving the link here for possible future references: https://github.com/idnow/de.idnow.android/issues/130

**Comment by adityasingh773** [comment]
This was somehow fixed in the latest release. Closing the issue now.

**Comment by reichhartd** [comment]
`v0.5.0`, as described by you above, is still the latest release.
Did you change any setting option?

**Comment by adityasingh773** [comment]
I did not
