### ISSUE TITLE
eID support

### ISSUE THREAD

**Issue by adeem** [tokenstreet-tech/react-native-idnow-videoident#615]
**Describe the solution you'd like**
IDNow also support eID feature and it would be great if you folks can support eID as well?

**Comment by reichhartd** [comment]
Hello @adeem,
thank you very much for the feature request. We do not have a contract with IDnow for the eID product, so we are not interested in offering this feature, and would not be able to test the written code.
If you are interested in implementing this feature, feel free to fork this repository.
