### ISSUE TITLE
new release for iOS 6.4.0 SDK

### ISSUE THREAD

**Issue by 343max** [tokenstreet-tech/react-native-idnow-videoident#885]
I noticed you already added the latest iOS SDK but haven't created a new release for that. Is there a reason why? Still hoping some of the issues I have with the current sdk will be fixed in the latest version.

**Comment by reichhartd** [comment]
I will release an update in the next few days. I still have to test this version with our environment.

**Comment by reichhartd** [comment]
I've just released [v0.21.0](https://github.com/tokenstreet-tech/react-native-idnow-videoident/releases/tag/v0.21.0). 🎉
Feel free to let me know if the iOS SDK release has solved any problems for you.
